#!/bin/bash

set -eux # -x for verbose logging to juju debug-log
juju-log "Installing ruby"
apt-add-repository -y ppa:brightbox/ruby-ng
apt-get -qq update
apt-get install -y -qq ruby1.9.1-dev 

juju-log "Installing ruby dependencies"
apt-get install -y build-essential openssl libreadline6 libreadline6-dev curl git-core \
zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev \
libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison

juju-log "Installing git"
apt-get install -y git

juju-log "Installing chef gem"
gem install chef

juju-log "clone chef recipts"
git clone https://github.com/Altoros/cf-vagrant-installer.git
